### ISSUE TITLE
我发现一个bug

### ISSUE THREAD

**Issue by xfhy** [gycold/SectionRecyclerViewAdapter#2]
当整个列表没有Footer的时候会出问题

**Comment by xfhy** [comment]
问题:最后那个分组的最后一项不会加载数据

**Comment by gycold** [comment]
@是的，没有footer的话需要设置一个公用的空的footer，base类没有默认有foot，如果需要footer为null，可以修改一下base类的逻辑，不复杂的

**Comment by xfhy** [comment]
嘿嘿,我修改了
